source 'https://rubygems.org'






# Core
gem 'rails', '4.2.7.1'
gem 'mysql2', '~> 0.3.18'

# Frontend
gem 'high_voltage', '~> 3.0.0'

# Admin
gem 'activeadmin', git: 'https://github.com/activeadmin/activeadmin'
gem 'net-ssh'
gem 'active_admin_theme'
gem 'country_select'
gem 'groupdate'
gem 'hightop'
gem 'active_median'
gem 'chartkick'
gem 'best_in_place', github: 'bernat/best_in_place'


# API
gem 'devise_token_auth'
gem 'omniauth'
gem 'active_model_serializers', '~> 0.10.0'
gem 'omniauth-facebook-access-token'
gem "koala", "~> 2.2"

# Upload
gem 'file_validators'
gem 'carrierwave', github: 'carrierwaveuploader/carrierwave'
gem 'mini_magick',             '3.8.0'
gem 'fog',                     '1.26.0'
gem 'fog-aws'
gem 'aws-sdk'

# Backend UI
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

# Stats
gem 'descriptive_statistics', '~> 2.4.0', :require => 'descriptive_statistics/safe'


# Env specitics
group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
